version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./data_source/dbdata:/var/lib/postgresql/data
      - ./data_source/data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432

  db_bi:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind_bi
      POSTGRES_USER: northwind_bi_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./destiny_db/dbanalytics:/var/lib/postgresql/data
    ports:
      - 5433:5432